name: test_release

on:
  pull_request:
  push:
    branches: [ master ]

env:
  TOKEN: ${{ secrets.DISCORDBOTTOKEN }}
  GUILDID: ${{ secrets.DISCORDGUILDID }} 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: TOKEN=$TOKEN go test -v ./...
